"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const path = require("path");
exports.PACKAGE_JSON_FILENAME = "package.json";
exports.TOOL_PACKAGE_JSON = require(`../../${exports.PACKAGE_JSON_FILENAME}`);
exports.TOOL_FULL_NAME = exports.TOOL_PACKAGE_JSON.name;
exports.TOOL_SHORT_NAME = exports.TOOL_FULL_NAME.split('/')[1];
exports.TOOL_VERSION = exports.TOOL_PACKAGE_JSON.version;
exports.CONFIG_FILE_NAME = `${exports.TOOL_SHORT_NAME}.json`;
exports.CONFIG_FILE_RELATIVE_PATH = `${exports.CONFIG_FILE_NAME}`;
exports.CONFIG_FILE_ABSOLUTE_PATH = path.resolve(exports.CONFIG_FILE_RELATIVE_PATH);
exports.MONOREPO_PACKAGE_JSON_RELATIVE_PATH = exports.PACKAGE_JSON_FILENAME;
exports.MONOREPO_PACKAGE_JSON_ABSOLUTE_PATH = path.resolve(exports.MONOREPO_PACKAGE_JSON_RELATIVE_PATH);
exports.TS_MONOREPO_FOLDER_RELATIVE_PATH = `.${exports.TOOL_SHORT_NAME}`;
exports.TS_MONOREPO_FOLDER_ABSOLUTE_PATH = path.resolve(exports.TS_MONOREPO_FOLDER_RELATIVE_PATH);
exports.TYPESCRIPT_LEAF_PACKAGES_CONFIG_FILE_NAME = "tsconfig-leaves.json";
exports.TYPESCRIPT_LEAF_PACKAGES_CONFIG_FILE_RELATIVE_PATH = `${exports.TS_MONOREPO_FOLDER_RELATIVE_PATH}/${exports.TYPESCRIPT_LEAF_PACKAGES_CONFIG_FILE_NAME}`;
exports.TYPESCRIPT_LEAF_PACKAGES_CONFIG_FILE_ABSOLUTE_PATH = path.resolve(exports.TYPESCRIPT_LEAF_PACKAGES_CONFIG_FILE_RELATIVE_PATH);
exports.PACKAGES_DIRECTORY_NAME = "packages";
exports.PACKAGES_DIRECTORY_RELATIVE_PATH = `${exports.PACKAGES_DIRECTORY_NAME}`;
exports.PACKAGE_NAME_CONFIG_PATH_REQUIRED_SUFFIX = "~";
exports.GLOBAL_SCOPE_NAME = "global-scope";
exports.TS_CONFIG_JSON_FILENAME = "tsconfig.json";
exports.TS_CONFIG_JSON_OUT_DIR = "./build";
exports.TS_CONFIG_JSON_ROOT_DIR = "./source";
exports.SUCCESS = Symbol("Success");
//# sourceMappingURL=constants.js.map