export declare const PACKAGE_JSON_FILENAME = "package.json";
export declare const TOOL_PACKAGE_JSON: any;
export declare const TOOL_FULL_NAME: string;
export declare const TOOL_SHORT_NAME: string;
export declare const TOOL_VERSION: string;
export declare const CONFIG_FILE_NAME: string;
export declare const CONFIG_FILE_RELATIVE_PATH: string;
export declare const CONFIG_FILE_ABSOLUTE_PATH: string;
export declare const MONOREPO_PACKAGE_JSON_RELATIVE_PATH = "package.json";
export declare const MONOREPO_PACKAGE_JSON_ABSOLUTE_PATH: string;
export declare const TS_MONOREPO_FOLDER_RELATIVE_PATH: string;
export declare const TS_MONOREPO_FOLDER_ABSOLUTE_PATH: string;
export declare const TYPESCRIPT_LEAF_PACKAGES_CONFIG_FILE_NAME = "tsconfig-leaves.json";
export declare const TYPESCRIPT_LEAF_PACKAGES_CONFIG_FILE_RELATIVE_PATH: string;
export declare const TYPESCRIPT_LEAF_PACKAGES_CONFIG_FILE_ABSOLUTE_PATH: string;
export declare const PACKAGES_DIRECTORY_NAME = "packages";
export declare const PACKAGES_DIRECTORY_RELATIVE_PATH: string;
export declare const PACKAGE_NAME_CONFIG_PATH_REQUIRED_SUFFIX = "~";
export declare const GLOBAL_SCOPE_NAME = "global-scope";
export declare const TS_CONFIG_JSON_FILENAME = "tsconfig.json";
export declare const TS_CONFIG_JSON_OUT_DIR = "./build";
export declare const TS_CONFIG_JSON_ROOT_DIR = "./source";
export declare const SUCCESS: unique symbol;
export declare type Success = typeof SUCCESS;
//# sourceMappingURL=constants.d.ts.map